//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invenietis.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vLCID
    {
        public short LCID { get; set; }
        public string Name { get; set; }
        public string EnglishName { get; set; }
        public string NativeName { get; set; }
        public string Fallbacks { get; set; }
        public string FallbacksLCID { get; set; }
        public string FallbacksNames { get; set; }
        public string FallbacksEnglishNames { get; set; }
        public string FallbacksNativeNames { get; set; }
    }
}
