//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invenietis.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vRes
    {
        public int ResId { get; set; }
        public string ResName { get; set; }
        public Nullable<int> ChildCount { get; set; }
        public Nullable<int> StringCount { get; set; }
        public Nullable<int> ParentResId { get; set; }
        public string ParentResName { get; set; }
        public Nullable<long> ParentLevel { get; set; }
    }
}
