//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invenietis.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vXLCIDResText
    {
        public int ResId { get; set; }
        public string ResName { get; set; }
        public short XLCID { get; set; }
        public string Value { get; set; }
    }
}
